---
Machine Learning with R
Chapter 02 - Managing and Understanding Data
---

### Vectors

```{r}
# - Contruct a set of vectors containing data on three medical patients
subject_name <- c("John Doe", "Jane Doe", "Steve Graves")
temperature <- c(98.1, 98.6, 101.4)
flu_status <- c(FALSE, FALSE, FALSE)

# - Vectors retain order
temperature[2]
temperature[2:3]
temperature[-2]
temperature[c(TRUE, TRUE, FALSE)]
```

### Factors
 
```{r}
# - A factor is special case of vector that is solely used for representing categorical or ordinal variables.
# - To create a factor from a character vector, simply apply the factor() function.

gender <- factor(c("MALE", "FEMALE", "MALE"))
gender

blood <- factor(c("O", "AB", "A"), levels=c("A", "AB", "O"))
blood

# - We can indicate the presence of ordinal data by providing the factor's levels in the disired order
symptoms <- factor(c("SEVERE", "MILD", "MODERATE"), levels=c("MILD", "MODERATE", "SEVERE"), ordered=TRUE)
symptoms
symptoms > "MODERATE"
```

### Lists

```{r}
# - Like a vecotr, stores a ordered collection of data, but can store mixed formats.

subject_name[1]
temperature[1]
flu_status[1]
gender[1]
blood[1]
symptoms[1]

subject1 <- list(
  fullname = subject_name[1],
  temperature = temperature[1],
  flu_status = flu_status[1],
  gender = gender[1],
  blood = blood[1],
  symptoms = symptoms[1]

)

subject1

subject1[2]
subject1[[2]]
subject1$temperature
subject1[c("temperature", "flu_status")]
```


### Data frames

```{r}
# - a dataframe is similar to a excel spreadsheet

pt_data <- data.frame(subject_name, temperature, 
                      flu_status, gender, blood, symptoms,
                      stringsAsFactors = FALSE)
pt_data

# - dataframes are two dimetions
pt_data$subject_name
pt_data[c("temperature", "flu_status")]

# - extract first row and second column
pt_data[1, 2]

# - you can use vectors to select multiple rows/columns
pt_data[c(1, 3), c(2, 4)]

# - extract the first column
pt_data[, 1]

# - extract the first row
pt_data[1, ]

# - extracting everything
pt_data[,]

# - or
pt_data[c(1, 3), c("temperature", "gender")]

# - negative numbers can be used to exclude data
pt_data[-2, c(-1, -3, -5, -6)]

# - create new columns
pt_data$temp_c <- (pt_data$temperature -32) * (5 /9)
pt_data[c("temperature", "temp_c")]
```


### Matrices and arrays

```{r}
# - A matrix is a data structure that represents a two dimensional table

m <- matrix(c(1, 2, 3, 4), nrow=2)
m

# Alternatively

m <- matrix(c(1, 2, 3, 4), ncol=2)
m

m <- matrix(c(1, 2, 3, 4, 5, 6), nrow=2)
m

m <- matrix(c(1, 2, 3, 4, 5, 6), ncol=2)
m

# You can extract value using [row, col]
m[1, ]
m[, 1]
```


## Managing data with R

### Saving, loading, and removing R data structures

```{r}
# - Save three objects: x, y, z to a file
# > save(x, y, z, file="mydata.RData")

# - Load the data using load
# > load("mydata.RData")

# List all of the data structures that are in the current session with ls()
ls()

# Remove data from session, like x and y
# > rm(x, y)

# You can also supply a vector of object names
rm(list = ls())
```


### Importing and saving data from CSV files

```{r}
# - tablular data (csv)

# - Reading a csv file into memory
# > pt_data <- read.csv("pt_data.csv", stringsAsFactors=FALSE)
# > pt_data <- read.csv("pt_data.csv", stringsAsFactors=FALSE, header=FALSE)
# > write.csv(pt_data, file="pt_data.csv", row.names=FALSE)
```


### Exploring and understanding data

```{r}
usedcars <- read.csv("usedcars.csv", stringsAsFactors = FALSE)
```


### Template

```{r}
```
