---
Machine Learning with R
Chapter 12 - Specialized Machine Learning Topics
---

  - <b>Topics</b>:
    - Unstructured or proprietary formats such as web pages, web APIs, spread-sheets, or databases
    - From a specialized domain such as bioinformatics or social network analysis
    - Too large to fit in memory or unable to complete analyses in a reasonable time

## Managining and preparing real-world data

  - The process of collecting, merging, sorting, filtering and reformatting data to meet requirements is called <b>data mugging</b> or <b>data wrangling</b>.

### Making data "tidy" with the tidyverse packages

  - <b>tidyverse</b>: collection of packages devoted to tidy data.
    - install.packages("tidyverse")

### Generalizing tabular data structures with tibble

  - <b>tibble</b> : acts almost like a data frame put includes additional functionality.
    - Convert a tibble to a data frame, using the as.data.frame() function.
    - Convert a dataframe to a tibble using the as_tibble() function.
  
```{r}
library(tibble)
credit <- read.csv("../ch05/credit.csv")
credit_tbl <- as_tibble(credit)

# - Take a look at the tibble object
credit_tbl
```

### Speeding and simplifying data preparation with dplyr

  - 

### 

  - 

